apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-workflow
  labels:
    app: test-workflow
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1723231393413
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-workflow
  template:
    metadata:
      labels:
        app: test-workflow
    spec:
      containers:
        - name: test-workflow
          image: acrworkflow1723231393413.azurecr.io/image-workflow-1723231393413:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
