apiVersion: v1
kind: Service
metadata:
  name: test-workflow
  namespace: namespace-workflow-1723231393413
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: test-workflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80